/**
 * @file Source code generated by PDL compiler.
 * @version 1.0
 * @sdkversion 5.0.302.813 (production_sdk#17c60b9.170725-1209)
 * @schemaversion 1.0.0.2
 */
/// <reference path="../TypeReferences.d.ts" />
/// <amd-bundling root="true" />

import FxComposition = MsPortalFx.Composition;
import PartSize = MsPortalFx.Parts.PartSize;
export = PartDefinitions;
module PartDefinitions {
    var extensionName: string = "Microsoft_Azure_Nginx";
}
