//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Portal.Extensions.Microsoft_Azure_Nginx.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Portal.Extensions.Microsoft_Azure_Nginx.Client.ProjectStrings", typeof(ProjectStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string AssetPropertyNames_Project_Location {
            get {
                return ResourceManager.GetString("AssetPropertyNames_Project_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource group.
        /// </summary>
        public static string AssetPropertyNames_Project_ResourceGroup {
            get {
                return ResourceManager.GetString("AssetPropertyNames_Project_ResourceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nginx.
        /// </summary>
        public static string AssetTypeNames_Project_lowerPlural {
            get {
                return ResourceManager.GetString("AssetTypeNames_Project_lowerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nginx.
        /// </summary>
        public static string AssetTypeNames_Project_lowerSingular {
            get {
                return ResourceManager.GetString("AssetTypeNames_Project_lowerSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nginx.
        /// </summary>
        public static string AssetTypeNames_Project_plural {
            get {
                return ResourceManager.GetString("AssetTypeNames_Project_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nginx.
        /// </summary>
        public static string AssetTypeNames_Project_singular {
            get {
                return ResourceManager.GetString("AssetTypeNames_Project_singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upstream servers.
        /// </summary>
        public static string AssetTypeNames_Service_lowerPlural {
            get {
                return ResourceManager.GetString("AssetTypeNames_Service_lowerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upstream server.
        /// </summary>
        public static string AssetTypeNames_Service_lowerSingular {
            get {
                return ResourceManager.GetString("AssetTypeNames_Service_lowerSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upstream Servers.
        /// </summary>
        public static string AssetTypeNames_Service_plural {
            get {
                return ResourceManager.GetString("AssetTypeNames_Service_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upstream Server.
        /// </summary>
        public static string AssetTypeNames_Service_singular {
            get {
                return ResourceManager.GetString("AssetTypeNames_Service_singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string ColumnTitle_Host {
            get {
                return ResourceManager.GetString("ColumnTitle_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnTitle_Name {
            get {
                return ResourceManager.GetString("ColumnTitle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string ColumnTitle_State {
            get {
                return ResourceManager.GetString("ColumnTitle_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ColumnTitle_Type {
            get {
                return ResourceManager.GetString("ColumnTitle_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string ColumnTitle_Updated {
            get {
                return ResourceManager.GetString("ColumnTitle_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string ColumnTitle_Weight {
            get {
                return ResourceManager.GetString("ColumnTitle_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the project is irreversible, would you like to continue?.
        /// </summary>
        public static string Command_Delete_Prompt {
            get {
                return ResourceManager.GetString("Command_Delete_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Command_Delete_Title {
            get {
                return ResourceManager.GetString("Command_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string detailsCommandTextResourceKey {
            get {
                return ResourceManager.GetString("detailsCommandTextResourceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name.
        /// </summary>
        public static string EnterTheName {
            get {
                return ResourceManager.GetString("EnterTheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://msdn.microsoft.com.
        /// </summary>
        public static string htmlSiteMSDNAddress {
            get {
                return ResourceManager.GetString("htmlSiteMSDNAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string Label_Internal {
            get {
                return ResourceManager.GetString("Label_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Property Label.
        /// </summary>
        public static string LinkPropertyLabel {
            get {
                return ResourceManager.GetString("LinkPropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string MenuItem_Overview {
            get {
                return ResourceManager.GetString("MenuItem_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string MenuItem_Properties {
            get {
                return ResourceManager.GetString("MenuItem_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string MenuItemKeyword_Location {
            get {
                return ResourceManager.GetString("MenuItemKeyword_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource group.
        /// </summary>
        public static string MenuItemKeyword_ResourceGroup {
            get {
                return ResourceManager.GetString("MenuItemKeyword_ResourceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources.
        /// </summary>
        public static string MenuItemKeyword_Resources {
            get {
                return ResourceManager.GetString("MenuItemKeyword_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string MenuItemKeyword_Status {
            get {
                return ResourceManager.GetString("MenuItemKeyword_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscription.
        /// </summary>
        public static string MenuItemKeyword_Subscription {
            get {
                return ResourceManager.GetString("MenuItemKeyword_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.microsoft.com.
        /// </summary>
        public static string MicrosoftUri {
            get {
                return ResourceManager.GetString("MicrosoftUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Nginx instance contains no upstream servers..
        /// </summary>
        public static string NoServicesInProject {
            get {
                return ResourceManager.GetString("NoServicesInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete of project &apos;{name}&apos; failed with status: &apos;{status}&apos; and error: &apos;{error}&apos;.
        /// </summary>
        public static string Operations_Delete_FailureDescription {
            get {
                return ResourceManager.GetString("Operations_Delete_FailureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed.
        /// </summary>
        public static string Operations_Delete_FailureTitle {
            get {
                return ResourceManager.GetString("Operations_Delete_FailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting project &apos;{name}&apos;.
        /// </summary>
        public static string Operations_Delete_InProgressDescription {
            get {
                return ResourceManager.GetString("Operations_Delete_InProgressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete in progress.
        /// </summary>
        public static string Operations_Delete_InProgressTitle {
            get {
                return ResourceManager.GetString("Operations_Delete_InProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting delete request for project &apos;{name}&apos;.
        /// </summary>
        public static string Operations_Delete_StartedDescription {
            get {
                return ResourceManager.GetString("Operations_Delete_StartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting delete request.
        /// </summary>
        public static string Operations_Delete_StartTitle {
            get {
                return ResourceManager.GetString("Operations_Delete_StartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted project &apos;{name}&apos;.
        /// </summary>
        public static string Operations_Delete_SuccessDescription {
            get {
                return ResourceManager.GetString("Operations_Delete_SuccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successful.
        /// </summary>
        public static string Operations_Delete_SuccessTitle {
            get {
                return ResourceManager.GetString("Operations_Delete_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete Project &apos;{0}&apos;. Please try again later..
        /// </summary>
        public static string Project_Delete_Failure_Message {
            get {
                return ResourceManager.GetString("Project_Delete_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted Project &apos;{0}&apos;..
        /// </summary>
        public static string Project_Delete_Success_Message {
            get {
                return ResourceManager.GetString("Project_Delete_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nginx subtitle.
        /// </summary>
        public static string ProjectBladeSubtitle {
            get {
                return ResourceManager.GetString("ProjectBladeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ProjectLocationColumn {
            get {
                return ResourceManager.GetString("ProjectLocationColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name must contain only alphanumeric characters.
        /// </summary>
        public static string ProjectNameAlphaNumeric {
            get {
                return ResourceManager.GetString("ProjectNameAlphaNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProjectNameColumn {
            get {
                return ResourceManager.GetString("ProjectNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project with this name already exists.
        /// </summary>
        public static string ProjectNameNotAvailable {
            get {
                return ResourceManager.GetString("ProjectNameNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is required.
        /// </summary>
        public static string ProjectNameRequired {
            get {
                return ResourceManager.GetString("ProjectNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PropertiesBladeTitle {
            get {
                return ResourceManager.GetString("PropertiesBladeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start Blade Subtitle.
        /// </summary>
        public static string QuickStartBladeSubtitle {
            get {
                return ResourceManager.GetString("QuickStartBladeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start Blade Title.
        /// </summary>
        public static string QuickStartBladeTitle {
            get {
                return ResourceManager.GetString("QuickStartBladeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start Description.
        /// </summary>
        public static string QuickStartDescription {
            get {
                return ResourceManager.GetString("QuickStartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section has an Icon and will open a new browser tab on click. These two factors are mutually exclusive as the first depends on if an iconUri is set and the second because section.selectable was populated. This description text is multiline..
        /// </summary>
        public static string QuickStartInfoListDesc1 {
            get {
                return ResourceManager.GetString("QuickStartInfoListDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDL provides openBlades and links[] of the InfoListBladeLinkContract type will be opened in blades. The tile supports both blade links and hyperlinks in the same section. Numbers are used when iconUri is not set..
        /// </summary>
        public static string QuickStartInfoListDesc2 {
            get {
                return ResourceManager.GetString("QuickStartInfoListDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon &amp; Selectable.
        /// </summary>
        public static string QuickStartInfoListTitle1 {
            get {
                return ResourceManager.GetString("QuickStartInfoListTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section that opens blade.
        /// </summary>
        public static string QuickStartInfoListTitle2 {
            get {
                return ResourceManager.GetString("QuickStartInfoListTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start.
        /// </summary>
        public static string QuickStartShortTitle {
            get {
                return ResourceManager.GetString("QuickStartShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start.
        /// </summary>
        public static string QuickStartTitle {
            get {
                return ResourceManager.GetString("QuickStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound.
        /// </summary>
        public static string ReferenceStatus_Bound {
            get {
                return ResourceManager.GetString("ReferenceStatus_Bound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string SectionHeader_Services {
            get {
                return ResourceManager.GetString("SectionHeader_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location.
        /// </summary>
        public static string SelectLocation {
            get {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a resource group.
        /// </summary>
        public static string SelectResourceGroup {
            get {
                return ResourceManager.GetString("SelectResourceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a subscription.
        /// </summary>
        public static string SelectSubscription {
            get {
                return ResourceManager.GetString("SelectSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Services and their high level properties.
        /// </summary>
        public static string ServicesListGridSummary {
            get {
                return ResourceManager.GetString("ServicesListGridSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsBladeTitle {
            get {
                return ResourceManager.GetString("SettingsBladeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscriptionId.
        /// </summary>
        public static string SubscriptionId {
            get {
                return ResourceManager.GetString("SubscriptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Property Label.
        /// </summary>
        public static string TextPropertyLabel {
            get {
                return ResourceManager.GetString("TextPropertyLabel", resourceCulture);
            }
        }
    }
}
