/**
 * @file Source code generated by PDL compiler.
 * @version 1.0
 * @sdkversion 5.0.302.813 (production_sdk#17c60b9.170725-1209)
 * @schemaversion 1.0.0.2
 */
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-dependency path="../../ProjectCreate/ViewModels/CreateBladeViewModel" />

export = Main;
module Main {
    "use strict";
    export var blade: MsPortalFx.Extension.BladeDefinition = {
  "name": "CreateBlade",
  "viewModelName": "ProjectCreate$CreateBladeViewModel",
  "lenses": [],
  "width": 0,
  "style": 3,
  "actionBar": {
    "name": "",
    "actionBarKind": 1,
    "bindings": []
  },
  "templateBlade": {
    "htmlTemplate": null,
    "parameterProvider": true,
    "partSize": 0,
    "htmlTemplateInline": {
      "file": "PCV3Form.html",
      "content": "<div class=\"msportalfx-form\"> <div data-bind=\"foreach: formElements\"> <div data-bind=\"formElement: $data\"></div> </div> </div>"
    },
    "styleSheets": []
  },
  "attributes": 0
};
}
