/**
 * @file Source code generated by PDL compiler.
 * @version 1.0
 * @sdkversion 5.0.302.813 (production_sdk#17c60b9.170725-1209)
 * @schemaversion 1.0.0.2
 */
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-dependency path="../../Deployments/ViewModels/DeploymentInfoPart" />

export = Main;
module Main {
    "use strict";
    export var blade: MsPortalFx.Extension.BladeDefinition = {
  "name": "DeploymentsBlade",
  "inputs": [
    "id"
  ],
  "viewModelName": "Deployments$DeploymentInfoPart",
  "lenses": [],
  "width": 2,
  "pinnable": false,
  "style": 1,
  "toolbar": {
    "source": {
      "valuesFrom": [
        {
          "referenceType": 0,
          "property": "content.commandBar"
        }
      ]
    }
  },
  "templateBlade": {
    "htmlTemplate": null,
    "partSize": 9,
    "htmlTemplateInline": {
      "file": "DeploymentInfoPart.html",
      "content": ""
    },
    "styleSheets": []
  },
  "attributes": 0
};
}
