/**
 * @file Source code generated by PDL compiler.
 * @version 1.0
 * @sdkversion 5.0.302.813 (production_sdk#17c60b9.170725-1209)
 * @schemaversion 1.0.0.2
 */
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-dependency path="Project/QuickStart/ViewModels/ProjectQuickStartBladeViewModel" />
/// <amd-dependency path="Project/QuickStart/ViewModels/ProjectQuickStartInfoListViewModel" />

export = Main;
module Main {
    "use strict";
    export var blade: MsPortalFx.Extension.BladeDefinition = {
  "name": "ProjectQuickStartBlade",
  "viewModelName": "Project$ProjectQuickStartBladeViewModel",
  "lenses": [
    {
      "name": "ProjectQuickStartBlade_lens1",
      "partInstances": [
        {
          "name": "QuickStartPart",
          "inline": {
            "styleSheets": [],
            "viewModel": "Project$ProjectQuickStartInfoListViewModel",
            "partKind": 23,
            "inputs": [],
            "bindings": [],
            "details": [
              {
                "invocationInputArguments": [
                  {
                    "valuesFrom": [
                      {
                        "referenceType": 0,
                        "property": "content.selection"
                      }
                    ]
                  }
                ]
              }
            ],
            "initialSize": 8
          }
        }
      ]
    }
  ],
  "width": 1,
  "locked": true,
  "style": 5,
  "attributes": 0
};
}
