/**
 * @file Source code generated by PDL compiler.
 * @version 1.0
 * @sdkversion 5.0.302.813 (production_sdk#17c60b9.170725-1209)
 * @schemaversion 1.0.0.2
 */
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-dependency path="../../_generated/adapters/blade/ServiceBladeAdapter" />

export = Main;
module Main {
    "use strict";
    export var blade: MsPortalFx.Extension.BladeDefinition = {
  "hasOnPinMethod": true,
  "name": "ServiceBlade",
  "inputs": [
    "id"
  ],
  "templateKeyInputs": [
    "id"
  ],
  "viewModelName": "Project$ServiceBladeAdapter",
  "lenses": [],
  "assetType": "Service",
  "assetIdInputProperty": "id",
  "pinnable": true,
  "initialDisplayState": 2,
  "style": 8,
  "toolbar": {
    "source": {
      "valuesFrom": [
        {
          "referenceType": 0,
          "property": "content.commandBar"
        }
      ]
    }
  },
  "templateBlade": {
    "htmlTemplate": null,
    "partSize": 9,
    "htmlTemplateInline": {
      "file": "Client\\_generated\\Project.pdl",
      "content": "<div data-bind='pcControl: essentials'></div>"
    },
    "partState": {
      "inputIdentityProperties": [
        "content.essentialsExpanded"
      ]
    },
    "styleSheets": [],
    "isV2": true
  },
  "attributes": 0
};
}
