/**
 * @file Source code generated by PDL compiler.
 * @version 1.0
 * @sdkversion 5.0.302.813 (production_sdk#17c60b9.170725-1209)
 * @schemaversion 1.0.0.2
 */
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-dependency path="../../Project/Settings/ViewModels/SettingsBladeViewModel" />

export = Main;
module Main {
    "use strict";
    export var blade: MsPortalFx.Extension.BladeDefinition = {
  "name": "SettingsBlade",
  "inputs": [
    "id"
  ],
  "viewModelName": "Project$SettingsBladeViewModel",
  "lenses": [],
  "initialDisplayState": 2,
  "toolbar": {
    "source": {
      "valuesFrom": [
        {
          "referenceType": 0,
          "property": "content.commandBar"
        }
      ]
    }
  },
  "templateBlade": {
    "htmlTemplate": null,
    "partSize": 0,
    "htmlTemplateInline": {
      "file": "SettingsTemplateBlade.html",
      "content": "<div>This is an example template blade that shows a link.</div> <div data-bind=\"pcControl:infoBox\"></div> "
    },
    "styleSheets": []
  },
  "attributes": 0
};
}
