/**
 * @file Source code generated by PDL compiler.
 * @version 1.0
 * @sdkversion 5.0.302.813 (production_sdk#17c60b9.170725-1209)
 * @schemaversion 1.0.0.2
 */
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-dependency path="Project/QuickStart/ViewModels/ProjectQuickStartPartViewModel" />

export = Main;
module Main {
    "use strict";
    export var part: MsPortalFx.Extension.PartTypeDefinition = {
  "styleSheets": [],
  "name": "ProjectQuickStartPart",
  "viewModel": "Project$ProjectQuickStartPartViewModel",
  "partKind": 21,
  "canUseOldInputVersions": false,
  "inputs": [],
  "bindings": [],
  "details": [
    {
      "blade": "ProjectQuickStartBlade"
    }
  ]
};
}
